- src/components/atoms/buttons/pagenationBtn/PagenationBtn.module.scss
- src/components/molecules/editDashboardName/editDashboardTitle.module.scss
- src/components/molecules/inviteList/InviteList.tsx
- src/components/molecules/inviteList/inviteList.module.scss
- src/components/molecules/members/Members.tsx
- src/components/molecules/members/members.module.scss
- src/pages/editdashboard.tsx
- src/styles/editDashboard.module.scss
#42 
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
페이지네이션 버튼의 보더 수정
edit페이지의 구성원 컴포넌트 작성
ex) feat/login -> dev
42 feature 대시보드 수정 페이지 컴포넌트작성 -> dev
> [Feat] edit페이지 구성원 컴포넌트 작성

- .editorconfig
- src/@types/index.d.ts
- src/@types/type.ts
- src/api/auth/authApi.ts
- src/api/axios.ts
- src/components/atoms/input/emailInput/EmailInput.tsx
- src/hooks/useSessionStorage.ts
- src/pages/login/index.tsx
- src/pages/login/login.module.scss
- src/pages/signUp/index.tsx
- src/pages/signUp/signUp.module.scss
- src/styles/_mixins.scss
closed #49 
- useSessionHook 훅으로 session에 User를 JSON으로 저장했습니다. 
- 로그인/회원가입 배경화면 등 css 수정헀습니다.
`49-feature-로그인회원가입-api-구현` -> `develop`
> [Feat] 로그인/회원가입 API 구현

- src/components/molecules/cardSection/CardSection.tsx
- src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
- src/components/molecules/modals/deleteColumnModal/DeleteColumnModal.tsx
- src/components/molecules/modals/editColumnModal/EditColumnModal.tsx
- src/components/molecules/myDashboardList/MyDashboardList.tsx
closed #31 
-[] 기능 삭제
-[] 버그 수정
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- 대시보드 컬럼 추가
- 대시보드 컬럼 수정
- 대시보드 컬럼 삭제
31-feature-컬럼-관련-기능-구현-> dev
> [Feat] 컬럼 관련 기능 구현

- src/components/atoms/logoWithTitle/LogoWithTitle.tsx
- src/components/atoms/logoWithTitle/logoWithTitle.module.scss
- src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
- src/components/molecules/header/headerMyDashboard/headerMyDashboard.module.scss
- src/components/molecules/inviteList/InviteList.tsx
- src/components/molecules/inviteList/inviteList.module.scss
- src/components/molecules/members/members.module.scss
- src/pages/editdashboard.tsx
- src/styles/editDashboard.module.scss
closed #42 
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
대시보드의 퍼블리싱을 완료했습니다.
헤더와 사이드바에서 리액트 리스폰시브를 사용해서 났던 오류들을 css로 대체해 해결했습니다.
ex) feat/login -> dev
42 feature 대시보드 수정 페이지 컴포넌트작성 -> dev
> [Feat] 대시보드 수정 컴포넌트 추가 및 렌더링 오류 수정

- src/@types/type.ts
- src/api/auth/authApi.ts
- src/api/axios.ts
- src/api/cards/cardApi.ts
- src/api/columns/columnApi.ts
- src/api/members/memberApi.ts
- src/components/atoms/buttons/button/index.tsx
- src/components/atoms/input/columnNameInput/ColumnNameInput.tsx
- src/components/atoms/input/createDoItYourselfCommonInput/CreateDoItYourselfInput.tsx
- src/components/atoms/input/createDoItYourselfCommonInput/createDoItYourselfInput.module.scss
- src/components/atoms/input/dateInput/CreateDoItYourselfDate.tsx
- src/components/atoms/input/dateInput/createDoItYourselfDate.module.scss
- src/components/atoms/input/descriptionInput/CreateDoItYourselfDescription.tsx
- src/components/atoms/input/titleInput/CreateDoItYourselfTitle.tsx
- src/components/molecules/card/Card.tsx
- src/components/molecules/cardSection/CardSection.tsx
- src/components/molecules/imageInput/ImageInput.tsx
- src/components/molecules/imageInput/imageInput.module.scss
- src/components/molecules/input/CreateDoItYourselfTag.tsx
- src/components/molecules/input/createDoItYourselfTag.module.scss
- src/components/molecules/managerDropDown/ManagerDropDown.tsx
- src/components/molecules/managerDropDown/managerDropDown.module.scss
- src/components/molecules/modals/createCardModal/CreateCardModal.tsx
- src/components/molecules/modals/createCardModal/createCardModal.module.scss
- src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
- src/components/molecules/modals/editColumnModal/EditColumnModal.tsx
- src/pages/login/index.tsx
#66 
(calendar css 변경이 필요해서 close 안하겠습니다!!!!)
`66-feature-할-일-생성-모달-구현` -> `develop`
- react-hook-form 라이브러리 사용을 위해 `forwardRef` 설정을 했습니다.
- 이미지 업로드 후에 Card를 생성하도록 Card API 설정을 했습니다.
- multipart로 이미지 업로드 하기 위한 Column API 설정을 했습니다.
- `CreateCardModal` 컴포넌트 내 formData를 API에 연결했습니다.
- 날짜 선택 시 `yyyy-MM-dd HH:mm`로 통일하도록 변경했습니다.
`import { format } from 'date-fns';` 이게 `react-datepicker` 라이브러리에서 사용되는 라이브러리입니다. 
이걸로 날짜 형식을 변경할 수 있습니다. 
+ 참고하실 사항 
아마 `Card` 컴포넌트?에 있는 날짜도 이 형식으로 변경하시는 게 좋을 것 같아요! 
지금은 `2024-03-20T02:56:46.642Z` 이런식으로 들어가있네용
> [Feat] 할 일 생성 모달 구현

- src/@types/type.ts
- src/api/members/memberApi.ts
- src/components/atoms/input/titleInput/CreateDoItYourselfTitle.tsx
- src/components/atoms/kebapMenu/KebapMenu.tsx
- src/components/atoms/kebapMenu/kebapMenu.module.scss
- src/components/molecules/card/Card.tsx
- src/components/molecules/card/card.module.scss
- src/components/molecules/cardDetailKebap/CardDetailKebap.tsx
- src/components/molecules/cardDetailKebap/cardDetailKebap.module.scss
- src/components/molecules/cardSection/CardSection.tsx
- src/components/molecules/managerDropDown/ManagerDropDown.tsx
- src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
- src/components/molecules/modals/createCardModal/CreateCardModal.tsx
- src/components/molecules/modals/deleteCardModal/DeleteCardModal.tsx
- src/components/molecules/modals/deleteCardModal/deleteCardModal.module.scss
- src/components/molecules/modals/editCardModal/EditCardModal.tsx
- src/components/molecules/myHeader/myHeader.module.scss
- src/pages/dashboard/[id]/index.tsx
- src/styles/dashboard.module.scss
closed #32 
32-feature-할일-관련-기능구형 -> dev 
- 할일 생성 담당자 드롭다운 데이터 연결
- 할일 삭제 기능
- 할일 상세 데이터 불러오기
- 할일 수정기능(아직 미완성)
할일 수정 모달을 불러올때 input들에 기존데이터들을 불러와야하는데 <CreateDoItYourselfTitle>과 같은 Input컴포넌트들과 어떻게 연결해야할까요? 제가 만든 컴포넌트가 아니라 여러 시도를 해봐도 감이 잘 안오네요ㅠㅠ
> [Feat] 할일 관련 기능구현

- src/components/atoms/input/commentInput/CreateDoItYourselfComment.tsx
- src/components/atoms/input/createDoItYourselfCommonTextarea/CreateDoItYourselfTextarea.tsx
- src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
- src/components/molecules/modals/cardDetailModal/cardDetailModal.module.scss
33-feature-댓글-관련-기능-구현 -> dev 
- 카드 상세 모달에서 댓글 목록 불러오기
- 댓글 생성 기능
- 댓글 수정 버튼 클릭 시 인풋창으로 변경 및 버튼 변경
- 댓글 삭제 기능
> [Feat] 댓글 관련 기능 구현

- src/components/atoms/profileIcon/ProfileIcon.tsx
- src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
- src/components/molecules/header/headerMyDashboard/headerMyDashboard.module.scss
- src/components/molecules/layout/index.tsx
- src/pages/dashboard/[id]/edit.tsx
- src/pages/dashboard/[id]/index.tsx
- src/pages/mydashboard/index.tsx
dev -> dev
헤더 컴포넌트가 페이지에 따라 레이아웃이 변하도록 변경했습니다.
멤버 리스트 칩은 조금만 기다려주세요,,ㅜㅠ
> ♻️ refactor: 헤더 컴포넌트 통합

- src/@types/type.ts
- src/api/cards/cardApi.ts
- src/components/molecules/editDashboardName/EditDashboardTitle.tsx
- src/components/molecules/modals/createCardModal/CreateCardModal.tsx
- src/components/molecules/modals/editCardModal/EditCardModal.tsx
#85
`85-fix-할-일-수정-모달-수정` -> `develop`
- 카드 수정 API 연동 기능 구현
- ID 타입 오류 수정
> [Fix] 할 일 수정 모달 수정

- src/components/atoms/column/ColumnComponent.tsx
- src/components/atoms/kebapMenu/KebapMenu.tsx
- src/components/molecules/card/Card.tsx
- src/components/molecules/cardDetailKebap/CardDetailKebap.tsx
- src/components/molecules/cardSection/CardSection.tsx
- src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
- src/components/molecules/modals/editCardModal/EditCardModal.tsx
- src/components/molecules/statusDropDown/StatusDropDown.tsx
- 할일 수정 모달 StatusDropDown에 데이터 못가져오는 오류 해결
> [Fix] 할일 수정 모달 StatusDropDown에 데이터 불러오기

- src/components/molecules/card/Card.tsx
- src/components/molecules/card/card.module.scss
- src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
- src/components/molecules/modals/cardDetailModal/cardDetailModal.module.scss
- 할일 카드 및 상세 모달 태그 부분 태그들이 붙어있는 오류 해결
- 태그 색상 랜덤 지정
- 할일 상세 모달 담당자 프로필 이미지 동그랗게 수정
- 할일 상세 모달 이미지 border-radius 수정
> [Fix] 할일 태그 및 프로필 이미지 css 수정

- src/components/atoms/kebapMenu/KebapMenu.tsx
- src/components/molecules/card/Card.tsx
- src/components/molecules/editDashboardName/EditDashboardTitle.tsx
- src/components/molecules/inviteList/InviteList.tsx
- src/components/molecules/managerDropDown/ManagerDropDown.tsx
- src/components/molecules/members/Members.tsx
- src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
- src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
- src/components/molecules/modals/deleteCardModal/DeleteCardModal.tsx
- src/components/molecules/modals/inviteMemberModal/InviteMemberModal.tsx
- src/components/molecules/statusDropDown/StatusDropDown.tsx
- src/pages/api/auth/[...nextauth].js
- src/pages/dashboard/[id]/index.tsx
- src/pages/signUp/index.tsx
closed #85
`85-fix-할-일-수정-모달-수정` -> `develop`
- map 사용된 곳에 key prop 설정
- Context를 사용하여 Dashboard 아이디를 가져오도록 수정
- 불필요한 console.log 제거
> [Fix] map 사용된 곳에 key prop 설정 등

- src/api/members/memberApi.ts
- src/components/molecules/editDashboardName/EditDashboardTitle.tsx
- src/components/molecules/inviteList/InviteList.tsx
- src/components/molecules/members/Members.tsx
- src/components/molecules/modals/inviteMemberModal/InviteMemberModal.tsx
- src/pages/dashboard/[id]/edit.tsx
> 🐛 fix: console.log삭제 및 컴포넌트 이름 수정

- src/components/molecules/card/Card.tsx
- src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
-card, CardDetailModal 배포 오류 수정
> fix: 배포 오류 수정

- src/components/molecules/header/headerAuth/HeaderAuth.tsx
- src/pages/index.tsx
> [Hotfix] useEffect, useRouter 클라이언트 훅을 HeaderAuth로 이동

- src/components/molecules/card/Card.tsx
- src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
- src/components/molecules/invitedDashboardList/InvitedDashboardList.tsx
- src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
> [Fix]: key prop 및 기타 오류 수정

- src/@types/type.ts
- src/api/members/memberApi.ts
- src/components/atoms/column/ColumnComponent.tsx
- src/components/atoms/kebapMenu/KebapMenu.tsx
- src/components/molecules/card/Card.tsx
- src/components/molecules/cardDetailKebap/CardDetailKebap.tsx
- src/components/molecules/cardSection/CardSection.tsx
- src/components/molecules/inviteList/InviteList.tsx
- src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
- src/components/molecules/modals/editCardModal/EditCardModal.tsx
- src/components/molecules/statusDropDown/StatusDropDown.tsx
- src/hooks/contexts.ts
- src/hooks/useAuth.ts
- src/pages/dashboard/[id]/index.tsx
- src/pages/mydashboard/index.tsx
- columns 오류 뜨는 거 고쳤습니다
- key prop 오류도 하나 남은 거 마저 고쳤습니다
> [Hotfix] Context를 사용하여 columns에 대한 Props Drilling 해소

- next.config.mjs
- src/components/atoms/input/commentInput/CreateDoItYourselfComment.tsx
- src/components/atoms/input/createDoItYourselfCommonTextarea/CreateDoItYourselfTextarea.tsx
> [Fix] CommentProps 타입 오류 해결

- src/api/cards/cardApi.ts
- src/components/atoms/column/ColumnComponent.tsx
- src/components/atoms/input/createDoItYourselfCommonTextarea/CreateDoItYourselfTextarea.tsx
- src/components/molecules/card/Card.tsx
- src/components/molecules/card/card.module.scss
- src/components/molecules/cardSection/CardSection.tsx
- src/components/molecules/imageInput/ImageInput.tsx
- src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
- src/components/molecules/modals/createCardModal/CreateCardModal.tsx
- src/components/molecules/modals/editCardModal/EditCardModal.tsx
- src/components/molecules/statusDropDown/StatusDropDown.tsx
- src/hooks/contexts.ts
- src/pages/dashboard/[id]/index.tsx
- 빌드 시 발생하는 타입 오류를 수정했습니다
- 카드 등록창 버그를 수정하고 디자인을 개선했습니다
- 너무 졸려요
> [Hotfix] 빌드 오류 해결 및 css 수정

- src/components/molecules/managerDropDown/ManagerDropDown.tsx
- src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
- src/components/molecules/modals/inviteMemberModal/InviteMemberModal.tsx
- src/hooks/contexts.ts
- src/pages/dashboard/[id]/edit.tsx
> [Fix] 관리 페이지에서 초대 안 되는 오류 수정
